name: Spring CI/CD with Maven
run-name: ${{ github.actor }} is testing CI/CD
on: [push]
jobs:
  CI-CD_with_Maven:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code to runner
        uses: actions/checkout@v3
      - name: Set up Java in runner
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD}}" | docker login -u "${{ secrets.DOCKER_USERNAME}}" --password-stdin
      - name: Build app
        id: build
        run: ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install
      - name: Deploy to Dockerhub
        run: ./mvnw deploy jib:build -P deploy-docker
      - name: Send jacoco report
        continue-on-error: true
        run: bash <(curl -s https://codecov.io/bash)