name: Spring CI/CD with Maven
run-name: ${{ github.actor }} is testing CI/CD
on: [push]
jobs:
  CI-CD_with_Maven:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code to runner
        uses: actions/checkout@v3
      - name: Set up Java in runner
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: echo "${{ secrets.DOCKER_PASSWORD}}" | docker login -u "${{ secrets.DOCKER_USERNAME}}" --password-stdin
      - run: ./mvnw clean install
      - run: ./mvnw deploy jib:build -P deploy-docker